name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - sprint-7
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
        
    steps:
      # Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Setup Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

        # Install Docker Compose
      - name: Install Docker Compose
        run: |
          curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      # Build Docker Compose Services
      - name: Build Docker Compose
        run: docker-compose -f ./docker-compose.yml build

      # Start Services in Background
      - name: Start Docker Compose
        run: docker-compose -f ./docker-compose.yml up -d

      # Install Java 17
      - name: Install Java 17
        run: |
          sudo apt update
          sudo apt install -y openjdk-17-jdk
          java -version
      
      # Install Maven
      - name: Install Maven
        run: |
          sudo apt update
          sudo apt install -y maven
          mvn -v  # Ensure Maven is installed correctly
      
      # Install dependencies for dms-backend (using Maven)
      - name: Install Dependencies for dms-backend
        run: |
          cd dms-backend
          mvn clean install
      
      # Run Unit Tests for dms-backend (using Maven)
      - name: Run Unit Tests for dms-backend
        run: |
          cd dms-backend
          mvn test

      # Stop and Cleanup
      - name: Stop Docker Compose
        if: always()
        run: docker-compose -f ./docker-compose.yml down --volumes
